/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package BankSystem;

import javax.swing.JOptionPane;

/**
 *
 * @author ITD-STU
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jTransfer = new javax.swing.JRadioButton();
        jSetoran = new javax.swing.JRadioButton();
        jPenarikan = new javax.swing.JRadioButton();
        jOK = new javax.swing.JButton();
        jbatal = new javax.swing.JButton();
        jKeluar = new javax.swing.JButton();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setText("Pilih Jenis Transaksi :");

        jTransfer.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTransfer.setText("Transfer");
        jTransfer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTransferActionPerformed(evt);
            }
        });

        jSetoran.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jSetoran.setText("Setoran");
        jSetoran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSetoranActionPerformed(evt);
            }
        });

        jPenarikan.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPenarikan.setText("Penarikan");
        jPenarikan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPenarikanActionPerformed(evt);
            }
        });

        jOK.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jOK.setText("OK");
        jOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jOKActionPerformed(evt);
            }
        });

        jbatal.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jbatal.setText("Batalkan");
        jbatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbatalActionPerformed(evt);
            }
        });

        jKeluar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jKeluar.setText("Keluar");
        jKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jKeluarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(jOK, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(124, 124, 124)
                        .addComponent(jbatal)
                        .addGap(112, 112, 112)
                        .addComponent(jKeluar, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(161, 161, 161)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTransfer)
                            .addComponent(jPenarikan)
                            .addComponent(jLabel1)
                            .addComponent(jSetoran))))
                .addContainerGap(129, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(jLabel1)
                .addGap(40, 40, 40)
                .addComponent(jTransfer)
                .addGap(34, 34, 34)
                .addComponent(jSetoran)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(jPenarikan)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jOK, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbatal, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jKeluar, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(100, 100, 100))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jPenarikanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPenarikanActionPerformed
        jSetoran.setSelected(false);
        jTransfer.setSelected(false);
    }//GEN-LAST:event_jPenarikanActionPerformed

    private void jKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jKeluarActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jKeluarActionPerformed

    private void jOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jOKActionPerformed
        if(jTransfer.isSelected()){
            Transfer _transfer = new Transfer();
            _transfer.setVisible(true);
            this.dispose();
        }else if(jPenarikan.isSelected()){
            Penarikan _penarikan = new Penarikan();
            _penarikan.setVisible(true);
            this.dispose();
        }else if(jSetoran.isSelected()){
            Setoran _setoran = new Setoran();
            _setoran.setVisible(true);
            this.dispose();
        }else {
            JOptionPane.showMessageDialog(null, "Pilih Jenis Transaksi !");
        }
    }//GEN-LAST:event_jOKActionPerformed

    private void jTransferActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTransferActionPerformed
        jSetoran.setSelected(false);
        jPenarikan.setSelected(false);
    }//GEN-LAST:event_jTransferActionPerformed

    private void jSetoranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSetoranActionPerformed
        jTransfer.setSelected(false);
        jPenarikan.setSelected(false);
    }//GEN-LAST:event_jSetoranActionPerformed

    private void jbatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbatalActionPerformed
        Login _login = new Login();
        _login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jbatalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JButton jKeluar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton jOK;
    private javax.swing.JRadioButton jPenarikan;
    private javax.swing.JRadioButton jSetoran;
    private javax.swing.JRadioButton jTransfer;
    private javax.swing.JButton jbatal;
    // End of variables declaration//GEN-END:variables
}
