/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package BankSystem;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author ITD-STU
 */
public class Transfer extends javax.swing.JFrame {

    int id_transfer = 0;
    String idnum;
    Connection con;
    Statement st;
    ResultSet rs;
    ResultSet rs1;
    ResultSet rs2;
    String nama;
    String uang;

    /**
     * Creates new form Transfer
     */
    public Transfer() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jnorektujuan = new javax.swing.JTextField();
        jTransfer1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jOke = new javax.swing.JButton();
        jBatalkan = new javax.swing.JButton();
        jKeluar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("Transfer");

        jLabel2.setText("Nomor Rekening Tujuan");

        jLabel3.setText("Jumlah Uang");

        jnorektujuan.setToolTipText("");
        jnorektujuan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jnorektujuanActionPerformed(evt);
            }
        });

        jTransfer1.setToolTipText("");

        jLabel4.setText("Rp.");

        jOke.setText("Oke");
        jOke.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jOkeActionPerformed(evt);
            }
        });

        jBatalkan.setText("Batalkan");
        jBatalkan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBatalkanActionPerformed(evt);
            }
        });

        jKeluar.setText("Keluar");
        jKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jKeluarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jOke, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(161, 161, 161)
                        .addComponent(jBatalkan, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jKeluar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                                .addComponent(jLabel4)
                                .addGap(31, 31, 31))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTransfer1, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jnorektujuan, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(83, 83, 83))
            .addGroup(layout.createSequentialGroup()
                .addGap(256, 256, 256)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jnorektujuan, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jTransfer1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(82, 82, 82)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jOke, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBatalkan, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jKeluar, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(95, 95, 95))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jOkeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jOkeActionPerformed
        // TODO add your handling code here:
        String no_rek = jnorektujuan.getText();
        //String no_rektujuan = jnorektujuan.getText();
        String jlh_uang = jTransfer1.getText();

        try {
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/bankdb", "root", "pbo");
            st = con.createStatement();

            //String sql = "SELECT * FROM datanasabah where " + "no_rek ='" + jnorekanda.getText()+ "'";
            

            //String sql1 = "SELECT * FROM datanasabah where " + "no_rek ='" + no_rektujuan + "'";
            //rs1 = st.executeQuery(sql1);
            if (no_rek != null && jlh_uang != null) {
                rs = st.executeQuery("SELECT * FROM transaksi");
                while (rs.next()) {
                    id_transfer++;
                }
                id_transfer++;
                idnum = Integer.toString(id_transfer);
                

                String sql = "SELECT saldo FROM datanasabah where no_rek='" + jnorektujuan.getText() + "'";

                ResultSet hasil = st.executeQuery(sql);
                hasil.last();
                int saldo = hasil.getInt("saldo");
                int saldo2 = saldo - Integer.valueOf(jTransfer1.getText());
                String saldo3 = String.valueOf(saldo2);

                st.executeUpdate("update datanasabah set saldo='" + saldo3 + "' where no_rek='" + jnorektujuan.getText() + "'");

                String sql1 = "INSERT INTO transaksi " + "(id_transaksi, no_rek, jlh_uang)" + "VALUES ('" + id_transfer + "', '" + no_rek + "', '" + jlh_uang + "')";
                st.executeUpdate(sql1);
                
                JOptionPane.showMessageDialog(null, "Transaksi Anda Mulai Diproses");

                

                nama = jnorektujuan.getText();
                uang = jTransfer1.getText();
                Transferljt1 _transferljt1 = new Transferljt1();
                _transferljt1.setVisible(true);
                this.dispose();
            }

        } catch (SQLException error) {
            JOptionPane.showMessageDialog(null, "Nomor Rekening Tidak Terdapat pada Sistem !!");
        }


    }//GEN-LAST:event_jOkeActionPerformed

    private void jBatalkanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBatalkanActionPerformed
        // TODO add your handling code here:
        Menu _menu = new Menu();
        _menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jBatalkanActionPerformed

    private void jKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jKeluarActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jKeluarActionPerformed

    private void jnorektujuanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jnorektujuanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jnorektujuanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Transfer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Transfer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Transfer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Transfer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Transfer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBatalkan;
    private javax.swing.JButton jKeluar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton jOke;
    private javax.swing.JTextField jTransfer1;
    private javax.swing.JTextField jnorektujuan;
    // End of variables declaration//GEN-END:variables
}
